services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    env_file:
      - .env.dev
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: npm run dev -- -H 0.0.0.0
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/styles:/app/styles
      - /app/node_modules
    env_file:
      - .env.dev
    environment:
      - HOST=0.0.0.0
      - PORT=3000
