services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.prod