version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports: ["8000:8000"]
    volumes: ["./backend:/app"]
    env_file: [".env.dev"]
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    build:
      context: ./frontend
      target: dev
    ports: ["3000:3000"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file: [".env.dev"]
    command: npm run dev -- -H 0.0.0.0
